name: 开发环境

on:
  workflow_dispatch:
    inputs:
      productIcon:
        default: ''
        required: false
        description: '应用图标'
      productName:
        default: 'talkai'
        required: false
        description: '应用名称'
        
# 全局环境变量
env:
  BRANCH: product

jobs:
  build:
    name: 编译应用
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3
        with:
          ref: ${{env.BRANCH}}

      - name: 配置环境
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 安装依赖
        run: npm install

      - name: 下载图标
        if: ${{ github.event.inputs.productIcon != '' }}
        run: |
          curl -f -o assets/icon.png ${{ github.event.inputs.productIcon }}

      - name: 编译应用
        run: npm run build
        env:
          PRODUCT_NAME: ${{ github.event.inputs.productName }}
      - run: ls -l release
      - name: 申请上传地址
        id: upload-url
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            contentType="application/octet-stream"
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            contentType="application/x-apple-diskimage"
          fi
          curl -X POST https://api.panshu.com.cn/base/oss/upload_url -H "Content-Type: application/json" -d "{\"contentType\": \"${contentType}\"}"

      - name: 解析上传地址
        id: parse-upload-url
        shell: bash
        run: echo "::set-output name=uploadUrl::$([[ $(jq -r '.data.uploadUrl' ${{ steps.upload-url.outputs.stdout }}) ]] )"

