name: 生产环境

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: false
        default: 'World'
      age:
        description: 'Your age'
        required: false
        default: '30'
      productIcon:
        default: ''
        required: false
        description: '应用图标'
      productName:
        default: 'talkai'
        required: false
        description: '应用名称'
        
# 全局环境变量
env:
  BRANCH: product

jobs:
  your-job:
    runs-on: windows-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3
        with:
          ref: ${{env.BRANCH}}
          
      - name: 环境预置
        run: |
          echo "Hello, ${{ github.event.inputs.name }}!"
          echo "You are ${{ github.event.inputs.age }} years old."
          # 下载图片

          # 定义名称
          PRODUCT_NAME=${{ github.event.inputs.productName }}

      - name: 安装依赖
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm i
        
      - name: 编译代码
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm i
          npm run build:win
          ls -l
          ls -l release
          
