name: 生产环境

on:
  workflow_dispatch:

jobs:
  your-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a script
        run: echo "Workflow triggered via API"
      - name: 环境检查
        run: |
          echo "Hello, ${{ github.event.inputs.name }}!"
          echo "You are ${{ github.event.inputs.age }} years old."
